services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=database'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=passowrd'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
